//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTrackerEntities : DbContext
    {
        public TimeTrackerEntities()
            : base("name=TimeTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nums> Nums { get; set; }
        public virtual DbSet<T_HR_Team> T_HR_Team { get; set; }
        public virtual DbSet<T_HR_TeamMember> T_HR_TeamMember { get; set; }
        public virtual DbSet<T_PM_Member> T_PM_Member { get; set; }
        public virtual DbSet<T_PM_Project> T_PM_Project { get; set; }
        public virtual DbSet<T_PM_Task> T_PM_Task { get; set; }
        public virtual DbSet<T_PM_UserTime> T_PM_UserTime { get; set; }
        public virtual DbSet<T_SD_Customer> T_SD_Customer { get; set; }
        public virtual DbSet<T_SD_CustomerTeam> T_SD_CustomerTeam { get; set; }
        public virtual DbSet<T_Sys_Department> T_Sys_Department { get; set; }
        public virtual DbSet<T_Sys_Function> T_Sys_Function { get; set; }
        public virtual DbSet<T_Sys_Function2Role> T_Sys_Function2Role { get; set; }
        public virtual DbSet<T_Sys_Log> T_Sys_Log { get; set; }
        public virtual DbSet<T_Sys_OperationLog> T_Sys_OperationLog { get; set; }
        public virtual DbSet<T_Sys_OperType> T_Sys_OperType { get; set; }
        public virtual DbSet<T_Sys_Roles> T_Sys_Roles { get; set; }
        public virtual DbSet<T_Sys_Status> T_Sys_Status { get; set; }
        public virtual DbSet<T_Sys_UserInfo> T_Sys_UserInfo { get; set; }
        public virtual DbSet<T_PM_ReportRecord> T_PM_ReportRecord { get; set; }
    }
}
